/**
 * @file    real_od.h
 * @author  Samuel Martel
 * @date    2024-04-24
 * @brief   This file exists for the purpose of including the OD.h file generated by CANopenEditor into C++ files.
 *
 * @copyright
 * This program is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License as published by the Free Software Foundation, either
 * version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 * You should have received a copy of the GNU General Public License along with this program. If
 * not, see <a href=https://www.gnu.org/licenses/>https://www.gnu.org/licenses/</a>.
 */


#ifndef FRASY_SRC_UTILS_COMMUNICATION_CAN_OPEN_REAL_OD_H
#define FRASY_SRC_UTILS_COMMUNICATION_CAN_OPEN_REAL_OD_H

#ifdef __cplusplus
extern "C"{
#endif
#include "OD.h"
#ifdef __cplusplus
}
#endif

#endif //FRASY_SRC_UTILS_COMMUNICATION_CAN_OPEN_REAL_OD_H
