--Sequence("CanOpen", function()
--    Test("MetaFunction", function()
--        Context.map.ibs.board1.od = nil
--        Context.map.ibs.board2.od = nil
--
--        Log.I("Board 1")
--        Print(Context.map.ibs.board1, 2)
--        Context.map.ibs.board1:foo()
--
--        Log.I("Board 2")
--        Print(Context.map.ibs.board2, 2)
--        Context.map.ibs.board2:foo()
--    end)
--end)
