Sequence("PIO", function()
    Test("Fixed Supply", function()
        local ib = Context.map.ibs.pio
        ib:Download(ib.od["Supply 3V3"]["Output Enable"], true)
        ib:Download(ib.od["Supply 5V"]["Output Enable"], true)
        ib:Download(ib.od["Supply 12V"]["Output Enable"], true)
        ib:Download(ib.od["Supply 24V"]["Output Enable"], true)
        Utils.sleep_for(5000)
        ib:Download(ib.od["Supply 3V3"]["Output Enable"], false)
        ib:Download(ib.od["Supply 5V"]["Output Enable"], false)
        ib:Download(ib.od["Supply 12V"]["Output Enable"], false)
        ib:Download(ib.od["Supply 24V"]["Output Enable"], false)
    end)
end)
